language: node_js
node_js:
  - "10"
before_install:
 - npm i -g npm@6.1.0
cache:
 directories:
   - "node_modules"
notifications:
   slack:
     easyemail:Sjvqcwm25jFhXxEdZirCDqRk
     on_pull_requests: false
